# Generated by Django 4.0 on 2021-12-16 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 12, 16, 13, 32, 56, 340123, tzinfo=utc))),
                ('file1', models.CharField(max_length=100)),
                ('file2', models.CharField(max_length=100)),
            ],
        ),
    ]
