# Generated by Django 4.0 on 2021-12-17 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='filename',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='default', upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
